package com.example.flows.commandscheduler.models

enum class Reason {
    // EXECUTION REASON
    COMMAND_HISTORY_WAS_EMPTY,
    COMMAND_WITH_THIS_ID_IS_NOT_PRESENT_IN_COMMAND_HISTORY,
    A_COMMAND_WITH_SAME_ID_EXISTS_BUT_DIFFERENT_FROM_CURRENT_INCOMING_COMMAND,
    MANUAL_CHANNEL,

    // REJECTION REASON
    COMMAND_WITH_SAME_ID_EXISTS_IN_COMMAND_HISTORY,
    DEVICE_IS_ALREADY_IN_COMMANDED_STATE
}